<script src="<?= base_url('assets/admin/'); ?>js/jquery.min.js"></script>
<script src="<?= base_url('assets/admin/'); ?>js/bootstrap-select.min.js"></script>
<script src="<?= base_url('assets/admin/'); ?>js/bootstrap.min.js"></script>
<script src="<?= base_url('assets/admin/'); ?>js/jquery.dataTables.min.js"></script>
<script src="<?= base_url('assets/admin/'); ?>js/dataTables.bootstrap.min.js"></script>
<script src="<?= base_url('assets/admin/'); ?>js/Chart.min.js"></script>
<script src="<?= base_url('assets/admin/'); ?>js/fileinput.js"></script>
<script src="<?= base_url('assets/admin/'); ?>js/chartData.js"></script>
<script src="<?= base_url('assets/admin/'); ?>js/main.js"></script>
<script src="<?= base_url('assets/'); ?>swal/sweetalert2.all.min1.js"></script>